
services:
  embedded_server:
    build: ./backend
    container_name: embedded_server
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
    networks:
      - cloud_ide_net

  proxy:
    build: ./reverse-proxy
    container_name: container_proxy
    ports:
      - "4000:80"
    restart: unless-stopped
    networks:
      - cloud_ide_net

networks:
  cloud_ide_net:
    name: cloud_ide_net 
    driver: bridge
    external: true
