services:
  embedded_server:
    build: ./backend
    container_name: embedded_server
    ports:
      - "3000:3000"
      - "3173:5173"
     
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped

  main_server:
    build: ./main-server
    container_name: main_server
    ports:
      - "5000:3000"
    volumes:
      - ./main-server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/dev_auth
      - JWT_SECRET=supersecurekey
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
